#!/bin/bash

mkdir -p $OPENSHIFT_DATA_DIR/npmcache

OLD_HOME=$HOME
export HOME=$OPENSHIFT_DATA_DIR/npmcache

cd "${OPENSHIFT_REPO_DIR}/server"
npm install

cd "${OPENSHIFT_REPO_DIR}/public"
npm install --dev
npm run typings -- install
npm run tsc
npm prune

export HOME=$OLD_HOME